config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :mains do
    resources :users
    get "listuser"
    get "listmanager"
  end
  resources :generics do 
    resources :users
    resources :generic_managers
  end
  resources :collegeaands do 
    resources :users
    resources :college_managers
  end
  resources :schooles do
    resources :users
    resources :schoole_managers
  end
  resources :assessments do
    resources :users
    resources :assessment_managers
  end
  resources :assessment_managers
  resources :generic_managers
  resources :college_managers
  resources :schoole_managers
  root to: "mains#index"
  

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  belongs_to :user
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]

  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all
    @users = User.all
    @assessment_managers = AssessmentManager.all
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to assessments_path, notice: 'Assessment Report was successfully created.' }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to assessments_path, notice: 'Assessment Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to assessments_url, notice: 'Assessment Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assessment_params
      params.require(:assessment).permit(:one, :two, :three, :four, :text, :five, :six, :seven, :eight, :nine, :ten, :user_id)
    end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_form.html.erb
<%= form_for(@assessment) do |f| %>
  <% if @assessment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

      <ul>
      <% @assessment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table align="center">
   <tr><td>
Date Submitted
  </td>	<td><div class="field">
    <% f.label :one %>
    <%= f.date_select :one %>
  </div>
           	</td>
           </tr><tr>	<td>
Department
  </td>	<td><div class="field">
    <% f.label :two %><br>
    <%= f.text_field :two %>
  </div>
           	</td>
           </tr><tr>	<td>
Degree/Type
  </td>	<td><div class="field">
    <% f.label :three %><br>
    <%= f.text_field :three %>
  </div>
           	</td>
           </tr><tr>	<td>
Contact Person (name,title, email)
  </td>	<td><div class="field">
    <% f.label :four %><br>
    <%= f.text_field :four %>
  </div>
           	</td>
           </tr><tr>	<td>
Date reviewed by CARC
  </td>	<td><div class="field">
    <% f.label :text %><br>
    <%= f.text_field :five %>
  </div>
           	</td>
           </tr><tr>	<td>
Program’s Assessment Plan (assessment of all SLOs) spans 1, 2, or 3 Assessment Cycles?
  </td>	<td><div class="field">
    <% f.label :six %><br>
    <%= f.text_area :six %>
  </div>
           	</td>
           </tr><tr>	<td>
What year in the Assessment Cycle (i.e., 1st, 2nd, or 3rd)?
  </td>	<td><div class="field">
    <% f.label :seven %><br>
    <%= f.text_area :seven %>
  </div>
           	</td>
           </tr><tr>	<td>
Action Plan from Previous Assessment Year: Describe the actions and/or plan revisions that were implemented during this reporting period in response to the previous period’s assessment results (e.g. what was implemented during F13-Sp14 as result of F12-Sp13’s reporting period?) Documentation required: Include documents such as updated syllabi, textbook changes, emails, meeting agendas, etc.
  </td>	<td><div class="field">
    <% f.label :eight %><br>
    <%= f.text_area :eight %>
  </div>
           	</td>
           </tr><tr>	<td>
Program Goal
  </td>	<td><div class="field">
    <% f.label :nine %><br>
    <%= f.text_area :nine %>
  </div>
           	</td>
           </tr><tr>	<td>
Program SLO (Assessed)
  </td>	<td><div class="field">
    <% f.label :ten %><br>
    <%= f.text_area :ten %>
  </div>
           	</td>
           </tr></table>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assessments/edit.html.erb
<h1>Editing Assessment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assessment %> |
<%= link_to 'Back', assessments_path %>

app/views/assessments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Annual Academic Program Assessment Reports
</h1>

<% if current_user.position == 'Admin' %>

<table border = '1'>
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
      <th>Text</th>
      <th>Five</th>
      <th>Six</th>
      <th>Seven</th>
      <th>Eight</th>
      <th>Nine</th>
      <th>Ten</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
        <td><%= assessment.one %></td>
        <td><%= assessment.two %></td>
        <td><%= assessment.three %></td>
        <td><%= assessment.four %></td>
        <td><%= assessment.text %></td>
        <td><%= assessment.five %></td>
        <td><%= assessment.six %></td>
        <td><%= assessment.seven %></td>
        <td><%= assessment.eight %></td>
        <td><%= assessment.nine %></td>
        <td><%= assessment.ten %></td>
        <% flag = 0 %>
            <% @assessment_managers.each do |assessment_manager| %>
              <% if assessment.id == assessment_manager.assessment_id %>
                <% flag = 1 %>
                <td><%= assessment_manager.comment %></td>
                <td><%= assessment_manager.score %></td>
                <td><%= link_to 'Grade', edit_assessment_assessment_manager_path(assessment, assessment_manager.id) %></td>
              <% end %>
            <% end %>
            <% if flag == 0 %>
                <td>Need to Grade</td>
                <td>Need to Grade</td>
                <td><%= link_to 'Grade', new_assessment_assessment_manager_path(assessment) %></td>
            <% end %>
        <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
        <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user.position == 'Manager' %>
<table border = "1">
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
      <th>Text</th>
      <th>Five</th>
      <th>Six</th>
      <th>Seven</th>
      <th>Eight</th>
      <th>Nine</th>
      <th>Ten</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% if current_user.department_name == user.department_name %>
        <% identity = user.id %>
        <% @assessments.each do |assessment| %>
          <tr>
          <% if identity == assessment.user_id %>
            <td><%= assessment.one %></td>
            <td><%= assessment.two %></td>
            <td><%= assessment.three %></td>
            <td><%= assessment.four %></td>
            <td><%= assessment.text %></td>
            <td><%= assessment.five %></td>
            <td><%= assessment.six %></td>
            <td><%= assessment.seven %></td>
            <td><%= assessment.eight %></td>
            <td><%= assessment.nine %></td>
            <td><%= assessment.ten %></td>
            <% flag = 0 %>
            <% @assessment_managers.each do |assessment_manager| %>
              <% if assessment.id == assessment_manager.assessment_id %>
                <% flag = 1 %>
                <td><%= assessment_manager.comment %></td>
                <td><%= assessment_manager.score %></td>
                <td><%= link_to 'Grade', edit_assessment_assessment_manager_path(assessment, assessment_manager.id) %></td>
              <% end %>
            <% end %>
            <% if flag == 0 %>
                <td>Need to Grade</td>
                <td>Need to Grade</td>
                <td><%= link_to 'Grade', new_assessment_assessment_manager_path(assessment) %></td>
            <% end %>
            <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
            <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user.position == 'User' %>

<table border = '1'>
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
      <th>Text</th>
      <th>Five</th>
      <th>Six</th>
      <th>Seven</th>
      <th>Eight</th>
      <th>Nine</th>
      <th>Ten</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
      <% if current_user.id == assessment.user_id %>
        <td><%= assessment.one %></td>
        <td><%= assessment.two %></td>
        <td><%= assessment.three %></td>
        <td><%= assessment.four %></td>
        <td><%= assessment.text %></td>
        <td><%= assessment.five %></td>
        <td><%= assessment.six %></td>
        <td><%= assessment.seven %></td>
        <td><%= assessment.eight %></td>
        <td><%= assessment.nine %></td>
        <td><%= assessment.ten %></td>
        <td><%= link_to 'Show', assessment %></td>
        <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
        <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Report', new_assessment_path %>
<% end %>

<br>
<%= link_to 'Back', mains_path %>

app/views/assessments/new.html.erb
<h1>New Assessment</h1>

<%= render 'form' %>

<%= link_to 'Back', assessments_path %>

app/views/assessments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>One:</strong>
  <%= @assessment.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @assessment.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @assessment.three %>
</p>

<p>
  <strong>Four:</strong>
  <%= @assessment.four %>
</p>

<p>
  <strong>Text:</strong>
  <%= @assessment.text %>
</p>

<p>
  <strong>Five:</strong>
  <%= @assessment.five %>
</p>

<p>
  <strong>Six:</strong>
  <%= @assessment.six %>
</p>

<p>
  <strong>Seven:</strong>
  <%= @assessment.seven %>
</p>

<p>
  <strong>Eight:</strong>
  <%= @assessment.eight %>
</p>

<p>
  <strong>Nine:</strong>
  <%= @assessment.nine %>
</p>

<p>
  <strong>Ten:</strong>
  <%= @assessment.ten %>
</p>


<%= link_to 'Edit', edit_assessment_path(@assessment) %> |
<%= link_to 'Back', assessments_path %>