config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :mains do
    resources :users
    get "listuser"
    get "listmanager"
  end
  resources :generics do 
    resources :users
    resources :generic_managers
  end
  resources :collegeaands do 
    resources :users
    resources :college_managers
  end
  resources :schooles do
    resources :users
    resources :schoole_managers
  end
  resources :assessments do
    resources :users
    resources :assessment_managers
  end
  resources :assessment_managers
  resources :generic_managers
  resources :college_managers
  resources :schoole_managers
  root to: "mains#index"
  

end

app/models/schoole_manager.rb
class SchooleManager < ActiveRecord::Base
  belongs_to :user
  belongs_to :schoole
end

app/controllers/schoole_managers_controller.rb
class SchooleManagersController < ApplicationController
  before_action :set_schoole_manager, only: [:show, :edit, :update, :destroy]

  # GET /schoole_managers
  # GET /schoole_managers.json
  def index
    @schoole_managers = SchooleManager.all
    @schooles = Schoole.all
  end

  # GET /schoole_managers/1
  # GET /schoole_managers/1.json
  def show
  end

  # GET /schoole_managers/new
  def new
    @schoole_manager = SchooleManager.new
    @schoole_managers = SchooleManager.all
    @schooles = Schoole.all
    @users = User.all
  end

  # GET /schoole_managers/1/edit
  def edit
    @schooles = Schoole.all
    @schoole_managers = SchooleManager.all
    @users = User.all
  end

  # POST /schoole_managers
  # POST /schoole_managers.json
  def create
    @schoole_manager = SchooleManager.new(schoole_manager_params)

    respond_to do |format|
      if @schoole_manager.save
        format.html { redirect_to schooles_path, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @schoole_manager }
      else
        format.html { render :new }
        format.json { render json: @schoole_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schoole_managers/1
  # PATCH/PUT /schoole_managers/1.json
  def update
    respond_to do |format|
      if @schoole_manager.update(schoole_manager_params)
        format.html { redirect_to schooles_path, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @schoole_manager }
      else
        format.html { render :edit }
        format.json { render json: @schoole_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schoole_managers/1
  # DELETE /schoole_managers/1.json
  def destroy
    @schoole_manager.destroy
    respond_to do |format|
      format.html { redirect_to schoole_managers_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schoole_manager
      @schoole_manager = SchooleManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schoole_manager_params
      params.require(:schoole_manager).permit(:user_id, :schoole_id, :comment, :score)
    end
end

app/helpers/schoole_managers_helper.rb
module SchooleManagersHelper
end

app/views/schoole_managers/_form.html.erb
<%= form_for(@schoole_manager) do |f| %>
  <% if @schoole_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schoole_manager.errors.count, "error") %> prohibited this schoole_manager from being saved:</h2>

      <ul>
      <% @schoole_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% s = request.original_url %>
  <% s = s[31...-21] %>
  <% s = s.to_i %>
  <% @schooles.each do |schoole| %>
    <% if schoole.id == s %>
    <p>
      <strong>Title of Degree or Certificate Program:</strong>
      <%= schoole.one %>
      <br>
      <strong>Degree Level:</strong>
      <%= schoole.two %>
      <br>
      <strong>Name of Academic Department:</strong>
      <%= schoole.three %>
      <br>
      <strong>Name of College/School/Branch:</strong>
      <%= schoole.four %>
      <br>
      <strong>Academic Year/Assessment Period:</strong>
      <%= schoole.five %>
      <br>
      <strong>Submitted By (include email address):</strong>
      <%= schoole.six %>
      <br>
      <strong>Date Submitted to College/School/Branch for Review:</strong>
      <%= schoole.seven %>
      <br>
      <strong>Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:</strong>
      <%= schoole.eight %>
      <br>
      <strong>State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:</strong>
      <%= schoole.nine %>
      <br>
      <strong>If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year: </strong>
      <%= schoole.ten %>
      <br>
    </p>
    <% end %>
  <% end %>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :schoole_id, :value => s %>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% if current_user.position == "Admin" %>
    <br>
    <% @schoole_managers.each do |schoolemanager| %>
      <% if schoolemanager.schoole_id == s %>
        <% ids = schoolemanager.user_id %>
        <% @users.each do |user| %>
          <% if ids == user.id %>
            <strong>Graded By </strong><%= user.email %>
            <strong>Under </strong><%= user.department_name %> Department
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/schoole_managers/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form' %>

<% s = request.original_url %>
<% s = s[31...-21] %>
<% s = s.to_i %>

<br>
<% @schooles.each do |schoole| %>
<% if schoole.id == s %>
<% @users.each do |user| %>
<% if schoole.user_id == user.id %>
<strong>Added By </strong><%= user.email %>
<strong>Under </strong><%= user.department_name %> Department
<% end %>
<% end %>
<% end %>
<% end %>

<%= link_to 'Back', schooles_path %>

app/views/schoole_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schoole Managers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Schoole</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schoole_managers.each do |schoole_manager| %>
      <tr>
        <td><%= schoole_manager.user %></td>
        <td><%= schoole_manager.schoole %></td>
        <td><%= schoole_manager.comment %></td>
        <td><%= schoole_manager.score %></td>
        <td><%= link_to 'Show', schoole_manager %></td>
        <td><%= link_to 'Edit', edit_schoole_manager_path(schoole_manager) %></td>
        <td><%= link_to 'Destroy', schoole_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schoole manager', new_schoole_manager_path %>

app/views/schoole_managers/new.html.erb
<h1>New Score</h1>

<%= render 'form' %>

<% s = request.original_url %>
<% s = s[31...-21] %>
<% s = s.to_i %>

<br>
<% @schooles.each do |schoole| %>
<% if schoole.id == s %>
<% @users.each do |user| %>
<% if schoole.user_id == user.id %>
<strong>Added By </strong><%= user.email %>
<strong>Under </strong><%= user.department_name %> Department
<% end %>
<% end %>
<% end %>
<% end %>


<%= link_to 'Back', schooles_path %>

app/views/schoole_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @schoole_manager.user %>
</p>

<p>
  <strong>Schoole:</strong>
  <%= @schoole_manager.schoole %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @schoole_manager.comment %>
</p>

<p>
  <strong>Score:</strong>
  <%= @schoole_manager.score %>
</p>

<%= link_to 'Edit', edit_schoole_manager_path(@schoole_manager) %> |
<%= link_to 'Back', schoole_managers_path %>