config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :mains do
    resources :users
    get "listuser"
    get "listmanager"
  end
  resources :generics do 
    resources :users
    resources :generic_managers
  end
  resources :collegeaands do 
    resources :users
    resources :college_managers
  end
  resources :schooles do
    resources :users
    resources :schoole_managers
  end
  resources :assessments do
    resources :users
    resources :assessment_managers
  end
  resources :assessment_managers
  resources :generic_managers
  resources :college_managers
  resources :schoole_managers
  root to: "mains#index"
  

end

app/models/collegeaand.rb
class Collegeaand < ActiveRecord::Base
	belongs_to :user
end

app/controllers/collegeaands_controller.rb
class CollegeaandsController < ApplicationController
  before_action :set_collegeaand, only: [:show, :edit, :update, :destroy]

  # GET /collegeaands
  # GET /collegeaands.json
  def index
    @collegeaands = Collegeaand.all
    @users = User.all
    @college_managers = CollegeManager.all
  end

  # GET /collegeaands/1
  # GET /collegeaands/1.json
  def show
  end

  # GET /collegeaands/new
  def new
    @collegeaand = Collegeaand.new
  end

  # GET /collegeaands/1/edit
  def edit
  end

  # POST /collegeaands
  # POST /collegeaands.json
  def create
    @collegeaand = Collegeaand.new(collegeaand_params)

    respond_to do |format|
      if @collegeaand.save
        format.html { redirect_to collegeaands_path, notice: 'College of Arts and Sciences Form was successfully created.' }
        format.json { render :show, status: :created, location: @collegeaand }
      else
        format.html { render :new }
        format.json { render json: @collegeaand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collegeaands/1
  # PATCH/PUT /collegeaands/1.json
  def update
    respond_to do |format|
      if @collegeaand.update(collegeaand_params)
        format.html { redirect_to collegeaands_path, notice: 'College of Arts and Sciences Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @collegeaand }
      else
        format.html { render :edit }
        format.json { render json: @collegeaand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collegeaands/1
  # DELETE /collegeaands/1.json
  def destroy
    @collegeaand.destroy
    respond_to do |format|
      format.html { redirect_to collegeaands_url, notice: 'College of Arts and Sciences Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collegeaand
      @collegeaand = Collegeaand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collegeaand_params
      params.require(:collegeaand).permit(:one, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :eleven, :twelve, :user_id)
    end
end

app/helpers/collegeaands_helper.rb
module CollegeaandsHelper
end

app/views/collegeaands/_form.html.erb
<%= form_for(@collegeaand) do |f| %>
  <% if @collegeaand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collegeaand.errors.count, "error") %> prohibited this collegeaand from being saved:</h2>

      <ul>
      <% @collegeaand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table align="center">
   <tr><td>

    Name of Degree or Certificate Program
    </td>	<td>
    <div class="field">
    <% f.label :one %>
    <%= f.text_field :one %>
  </div></td>
           </tr><tr>	<td>
    Degree Level</td>	<td>
    <div class="field">
    <% f.label :two %>
    <%= f.text_field :two %>
  </div></td>
                   </tr><tr>	<td>
    Name of Academic Department (if not a standalone program):</td>	<td>
  <div class="field">
    <% f.label :three %>
    <%= f.text_field :three %>
  </div></td>
                           </tr><tr>	<td>
    Name of College/School/Branch:</td>	<td>
  <div class="field">
      <% f.label :four %>
    <%= f.text_field :four %>
  </div></td>
                                   </tr><tr>	<td>
    Academic Year/Assessment Period:</td>	<td>
  <div class="field">
      <% f.label :five %>
    <%= f.text_field :five %>
  </div></td>
                                   </tr><tr>	<td>
    Submitted By (include email address):</td>	<td>
  <div class="field">
      <% f.label :six %>
    <%= f.text_field :six %>
  </div></td>
                                   </tr><tr>	<td>
    Date Submitted to College/School/Branch for Review:</td>	<td>
  <div class="field">
      <% f.label :seven %>
    <%= f.date_select :seven %>
  </div></td>
                                   </tr><tr>	<td>
    Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:</td>	<td>
  <div class="field">
      <% f.label :eight %>
    <%= f.date_select :eight %>
  </div></td>
                                   </tr><tr>	<td>
    State whether ALL of the program’s student learning outcomes (SLOs) are assessed over one year, two years, OR three years:</td>	<td>
  <div class="field">
      <% f.label :nine %>
    <%= f.text_area :nine %>
  </div></td>
                                   </tr><tr>	<td>
    If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year of your assessment cycle:
  <div class="field">
      </td>	<td><% f.label :ten %>
    <%= f.text_area :ten %>
  </div></td>
                                   </tr><tr>	<td>
    Describe the program changes that were implemented during this reporting period in response to the previous period’s assessment results. Please include evidence of implemented changes in an appendix:
  <div class="field">
      </td>	<td><% f.label :eleven %>
    <%= f.text_area :eleven %>
  </div></td>
                                   </tr><tr>	<td>
    Describe any revisions to your assessment process that you made for this reporting cycle and/or plan to make for future reporting cycles:
  <div class="field">
      </td>	<td><% f.label :twelve %>
    <%= f.text_area :twelve %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div></td>
                                   </tr></table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collegeaands/edit.html.erb
<h1>Editing College of Arts & Sciences Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @collegeaand %> |
<%= link_to 'Back', collegeaands_path %>

app/views/collegeaands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing College of Arts & Sciences Form</h1>
<% if current_user.position == 'Admin' %>
<table border="1">
  <thead>
    <tr>
      <th>Name of Degree or Certificate Program</th>
      <th>Name of Academic Department (if not a standalone program):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @collegeaands.each do |collegeaand| %>
      <tr>
        <td><%= collegeaand.one %></td>
        <td><%= collegeaand.three %></td>
        <td><%= collegeaand.seven %></td>
        <% flag = 0 %>
        <% @college_managers.each do |college_manager| %>
          <% if collegeaand.id == college_manager.collegeaand_id %>
            <% flag = 1 %>
            <td><%= college_manager.comment %></td>
            <td><%= college_manager.score %></td>
            <td><%= link_to 'Grade', edit_collegeaand_college_manager_path(college_manager.id, collegeaand) %></td>
          <% end %>
        <% end %>
        <% if flag == 0 %>
          <td>Need to Grade</td>
          <td>Need to Grade</td>
          <td><%= link_to 'Grade', new_collegeaand_college_manager_path(collegeaand) %></td>
        <% end %>
        <td><%= link_to 'Edit', edit_collegeaand_path(collegeaand) %></td>
        <td><%= link_to 'Destroy', collegeaand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% if current_user.position == 'Manager' %>
<table border="1">
  <thead>
    <tr>
      <th>Name of Degree or Certificate Program</th>
      <th>Name of Academic Department (if not a standalone program):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead
  <tbody>
    <% @users.each do |user| %>
      <% if current_user.department_name == user.department_name %>
        <% identity = user.id %>
        <% @collegeaands.each do |collegeaand| %>
          <tr>
          <% if identity == collegeaand.user_id %>
            <td><%= collegeaand.one %></td>
            <td><%= collegeaand.three %></td>
            <td><%= collegeaand.seven %></td>
            <% flag = 0 %>
            <% @college_managers.each do |college_manager| %>
              <% if collegeaand.id == college_manager.collegeaand_id %>
                <% flag = 1 %>
                <td><%= college_manager.comment %></td>
                <td><%= college_manager.score %></td>
                <td><%= link_to 'Grade', edit_collegeaand_college_manager_path(collegeaand, college_manager.id) %></td>
              <% end %>
            <% end %>
            <% if flag == 0 %>
              <td>Need to Grade</td>
              <td>Need to Grade</td>
              <td><%= link_to 'Grade', new_collegeaand_college_manager_path(collegeaand) %></td>
            <% end %>
            <td><%= link_to 'Edit', edit_collegeaand_path(collegeaand) %></td>
            <td><%= link_to 'Destroy', collegeaand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%end%>

<% if current_user.position == 'User' %>
<table border="1">
  <thead>
    <tr>
      <th>Name of Degree or Certificate Program</th>
        <th>Degree Level</th>
        <th>Name of Academic Department (if not a standalone  program): </th>
        <th>Name of College/School/Branch:</th>
        <th>Academic Year/Assessment Period: </th>
        <th>Submitted By (include email address): </th>
        <th>Date Submitted to College/School/Branch for Review:</th>
        <th>Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:</th>
        <th>State whether ALL of the program’s student learning outcomes (SLOs) are assessed over one year, two years, OR three years:</th>
        <th>If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year of your assessment cycle: </th>
        <th>Describe the program changes that were implemented during this reporting period in response to the previous period’s assessment results. Please include evidence of implemented changes in an appendix:</th>
        <th>Describe any revisions to your assessment process that you made for this reporting cycle and/or plan to make for future reporting cycles:</th>
        <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @collegeaands.each do |collegeaand| %>
      <tr>
      <% if current_user.id == collegeaand.user_id %>
        <td><%= collegeaand.one %></td>
        <td><%= collegeaand.two %></td>
        <td><%= collegeaand.three %></td>
        <td><%= collegeaand.four %></td>
        <td><%= collegeaand.five %></td>
        <td><%= collegeaand.six %></td>
        <td><%= collegeaand.seven %></td>
        <td><%= collegeaand.eight %></td>
        <td><%= collegeaand.nine %></td>
        <td><%= collegeaand.ten %></td>
        <td><%= collegeaand.eleven %></td>
        <td><%= collegeaand.twelve %></td>
        <td><%= link_to 'Show', collegeaand %></td>
        <td><%= link_to 'Edit', edit_collegeaand_path(collegeaand) %></td>
        <td><%= link_to 'Destroy', collegeaand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New College of Arts & Sciences Form', new_collegeaand_path %>
<% end %>

<br>
<%= link_to 'Back', mains_path %>

app/views/collegeaands/new.html.erb
<h1>New College of Arts & Sciences Form</h1>

<%= render 'form' %>

<%= link_to 'Back', collegeaands_path %>

app/views/collegeaands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>One:</strong>
  <%= @collegeaand.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @collegeaand.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @collegeaand.three %>
</p>

<p>
  <strong>Four:</strong>
  <%= @collegeaand.four %>
</p>

<p>
  <strong>Five:</strong>
  <%= @collegeaand.five %>
</p>

<p>
  <strong>Six:</strong>
  <%= @collegeaand.six %>
</p>

<p>
  <strong>Seven:</strong>
  <%= @collegeaand.seven %>
</p>

<p>
  <strong>Eight:</strong>
  <%= @collegeaand.eight %>
</p>

<p>
  <strong>Nine:</strong>
  <%= @collegeaand.nine %>
</p>

<p>
  <strong>Ten:</strong>
  <%= @collegeaand.ten %>
</p>

<p>
  <strong>Eleven:</strong>
  <%= @collegeaand.eleven %>
</p>

<p>
  <strong>Twelve:</strong>
  <%= @collegeaand.twelve %>
</p>

<%= link_to 'Edit', edit_collegeaand_path(@collegeaand) %> |
<%= link_to 'Back', collegeaands_path %>