config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :mains do
    resources :users
    get "listuser"
    get "listmanager"
  end
  resources :generics do 
    resources :users
    resources :generic_managers
  end
  resources :collegeaands do 
    resources :users
    resources :college_managers
  end
  resources :schooles do
    resources :users
    resources :schoole_managers
  end
  resources :assessments do
    resources :users
    resources :assessment_managers
  end
  resources :assessment_managers
  resources :generic_managers
  resources :college_managers
  resources :schoole_managers
  root to: "mains#index"
  

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  belongs_to :user
end

app/models/assessment_manager.rb
class AssessmentManager < ActiveRecord::Base
  belongs_to :user
  belongs_to :assessment
end

app/models/college_manager.rb
class CollegeManager < ActiveRecord::Base
  belongs_to :user
  belongs_to :collegeaand
end

app/models/collegeaand.rb
class Collegeaand < ActiveRecord::Base
	belongs_to :user
end

app/models/generic.rb
class Generic < ActiveRecord::Base
	belongs_to :user
end

app/models/generic_manager.rb
class GenericManager < ActiveRecord::Base
  belongs_to :user
  belongs_to :generic
end

app/models/schoole.rb
class Schoole < ActiveRecord::Base
	belongs_to :user
end

app/models/schoole_manager.rb
class SchooleManager < ActiveRecord::Base
  belongs_to :user
  belongs_to :schoole
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :generics
  has_many :collegeaands
  has_many :schooles
end

app/controllers/generics_controller.rb
class GenericsController < ApplicationController
  before_action :set_generic, only: [:show, :edit, :update, :destroy]

  # GET /generics
  # GET /generics.json
  def index
    @generics = Generic.all
    @users = User.all
    @generic_managers = GenericManager.all
  end

  # GET /generics/1
  # GET /generics/1.json
  def show
  end

  # GET /generics/new
  def new
    @generic = Generic.new
  end

  # GET /generics/1/edit
  def edit
  end

  # POST /generics
  # POST /generics.json
  def create
    @generic = Generic.new(generic_params)

    respond_to do |format|
      if @generic.save
        format.html { redirect_to generics_path, notice: 'UNM Generic form was successfully created.' }
        format.json { render :show, status: :created, location: @generic }
      else
        format.html { render :new }
        format.json { render json: @generic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generics/1
  # PATCH/PUT /generics/1.json
  def update
    respond_to do |format|
      if @generic.update(generic_params)
        format.html { redirect_to generics_path, notice: 'UNM Generic form was successfully updated.' }
        format.json { render :show, status: :ok, location: @generic }
      else
        format.html { render :edit }
        format.json { render json: @generic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generics/1
  # DELETE /generics/1.json
  def destroy
    @generic.destroy
    respond_to do |format|
      format.html { redirect_to generics_url, notice: 'UNM Generic form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_generic
      @generic = Generic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def generic_params
      params.require(:generic).permit(:one, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :eleven, :user_id)
    end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
	@users = User.all
end

app/controllers/schooles_controller.rb
class SchoolesController < ApplicationController
  before_action :set_schoole, only: [:show, :edit, :update, :destroy]

  # GET /schooles
  # GET /schooles.json
  def index
    @schooles = Schoole.all
    @users = User.all
    @schoole_managers = SchooleManager.all
  end

  # GET /schooles/1
  # GET /schooles/1.json
  def show
  end

  # GET /schooles/new
  def new
    @schoole = Schoole.new
  end

  # GET /schooles/1/edit
  def edit
  end

  # POST /schooles
  # POST /schooles.json
  def create
    @schoole = Schoole.new(schoole_params)

    respond_to do |format|
      if @schoole.save
        format.html { redirect_to schooles_path, notice: 'School of Engineering Form was successfully created.' }
        format.json { render :show, status: :created, location: @schoole }
      else
        format.html { render :new }
        format.json { render json: @schoole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schooles/1
  # PATCH/PUT /schooles/1.json
  def update
    respond_to do |format|
      if @schoole.update(schoole_params)
        format.html { redirect_to schooles_path, notice: 'Schoo of Engineering Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @schoole }
      else
        format.html { render :edit }
        format.json { render json: @schoole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schooles/1
  # DELETE /schooles/1.json
  def destroy
    @schoole.destroy
    respond_to do |format|
      format.html { redirect_to schooles_url, notice: 'School of Engineering Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schoole
      @schoole = Schoole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schoole_params
      params.require(:schoole).permit(:one, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/college_managers_helper.rb
module CollegeManagersHelper
end

app/helpers/collegeaands_helper.rb
module CollegeaandsHelper
end

app/helpers/generic_managers_helper.rb
module GenericManagersHelper
end

app/helpers/generics_helper.rb
module GenericsHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/schoole_managers_helper.rb
module SchooleManagersHelper
end

app/helpers/schooles_helper.rb
module SchoolesHelper
end

app/views/generics/_form.html.erb
<%= form_for(@generic) do |f| %>
  <% if @generic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@generic.errors.count, "error") %> prohibited this generic from being saved:</h2>

      <ul>
      <% @generic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table align="center">
   <tr><td>
       Title of Degree or Certificate Program
       </td>	<td><div class="field"><% f.label :one %>
       <%= f.text_field :one %></div>
   	</td>
   </tr><tr>	<td>
       Degree Level
       </td>	<td><div class="field"><% f.label :two %>
       <%= f.text_field :two %></div>
     </td>
   </tr><tr>	<td>
       Name of Academic Department (if relevant):
       </td>
   	<td><div class="field"><% f.label :three %>
       <%= f.text_field :three %></div>
     </td>
   </tr><tr>	<td>

       Name of College/School/Branch:
       </td>
   	<td><div class="field"><% f.label :four %>
       <%= f.text_field :four %></div>
     </td>
   </tr><tr>	<td>

       Academic Year/Assessment Period:
       </td>
   	<td><div class="field"><% f.label :five %>
       <%= f.text_field :five %></div>
     </td>
   </tr><tr>	<td>

       Submitted By (include email address):
       </td>
   	<td><div class="field"><% f.label :six %>
       <%= f.text_field :six %></div>
     </td>
   </tr><tr>	<td>

       Date Submitted to College/School/Branch for Review:
       </td>
   	<td><div class="field"><% f.label :seven %>
       <%= f.date_select :seven %></div>
     </td>
   </tr><tr>	<td>

       Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:
       </td>
   	<td><div class="field"><% f.label :eight %>
       <%= f.date_select :eight %></div>
     </td>
   </tr><tr>	<td>

       State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:
       </td>
   	<td><div class="field"><% f.label :nine %>
       <%= f.text_area :nine %></div>
     </td>
   </tr><tr>	<td>

       If the program’s SLO1’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year:
       </td>
   	<td><div class="field"><% f.label :ten %>
       <%= f.text_area :ten %></div>
     </td>
   </tr><tr>	<td>

       Describe the actions and/or improvements that were implemented during the previous reporting period (provide relevant evidence):
       </td>
   	<td><div class="field"><% f.label :eleven %>
       <%= f.text_area :eleven %></div>
     </td></tr>
   	</table>
     <%= f.hidden_field :user_id, value: current_user.id %>
     <div class="actions">
       <%= f.submit %>
     </div>
   <% end %>

app/views/generics/edit.html.erb
<h1>Editing Generic</h1>

<%= render 'form' %>

<%= link_to 'Show', @generic %> |
<%= link_to 'Back', generics_path %>

app/views/generics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing UNM Generic Forms </h1>

<% if current_user.position == 'Admin' %>

<table border = '1'>
  <thead>
    <tr>
      <th>Title of Degree or Certificate Program</th>
      <th>Name of Academic Department (if relevant):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @generics.each do |generic| %>
      <tr>
        <td><%= generic.one %></td>
        <td><%= generic.three %></td>
        <td><%= generic.seven %></td>
        <% flag = 0 %>
            <% @generic_managers.each do |generic_manager| %>
              <% if generic.id == generic_manager.generic_id %>
                <% flag = 1 %>
                <td><%= generic_manager.comment %></td>
                <td><%= generic_manager.score %></td>
                <td><%= link_to 'Grade', edit_generic_generic_manager_path(generic, generic_manager.id) %></td>
              <% end %>
            <% end %>
            <% if flag == 0 %>
                <td>Need to Grade</td>
                <td>Need to Grade</td>
                <td><%= link_to 'Grade', new_generic_generic_manager_path(generic) %></td>
            <% end %>
        <td><%= link_to 'Edit', edit_generic_path(generic) %></td>
        <td><%= link_to 'Destroy', generic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user.position == 'Manager' %>
<table border = "1">
  <thead>
    <tr>
      <th>Title of Degree or Certificate Program</th>
      <th>Name of Academic Department (if relevant):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% if current_user.department_name == user.department_name %>
        <% identity = user.id %>
        <% @generics.each do |generic| %>
          <tr>
          <% if identity == generic.user_id %>
            <td><%= generic.one %></td>
            <td><%= generic.three %></td>
            <td><%= generic.seven %></td>
            <% flag = 0 %>
            <% @generic_managers.each do |generic_manager| %>
              <% if generic.id == generic_manager.generic_id %>
                <% flag = 1 %>
                <td><%= generic_manager.comment %></td>
                <td><%= generic_manager.score %></td>
                <td><%= link_to 'Grade', edit_generic_generic_manager_path(generic, generic_manager.id) %></td>
              <% end %>
            <% end %>
            <% if flag == 0 %>
                <td>Need to Grade</td>
                <td>Need to Grade</td>
                <td><%= link_to 'Grade', new_generic_generic_manager_path(generic) %></td>
            <% end %>
            <td><%= link_to 'Edit', edit_generic_path(generic) %></td>
            <td><%= link_to 'Destroy', generic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user.position == 'User' %>

<table border = '1'>
  <thead>
    <tr>
      <th>Title of Degree or Certificate Program</th>
      <th>Degree Level</th>
      <th>Name of Academic Department (if relevant):</th>
      <th>Name of College/School/Branch:</th>
      <th>Academic Year/Assessment Period:</th>
      <th>Submitted By (include email address):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:</th>
      <th>State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:</th>
      <th>If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year:</th>
      <th>Describe the actions and/or improvements that were implemented during the previous reporting period (provide relevant evidence):</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @generics.each do |generic| %>
      <tr>
      <% if current_user.id == generic.user_id %>
        <td><%= generic.one %></td>
        <td><%= generic.two %></td>
        <td><%= generic.three %></td>
        <td><%= generic.four %></td>
        <td><%= generic.five %></td>
        <td><%= generic.six %></td>
        <td><%= generic.seven %></td>
        <td><%= generic.eight %></td>
        <td><%= generic.nine %></td>
        <td><%= generic.ten %></td>
        <td><%= generic.eleven %></td>
        <td><%= link_to 'Show', generic %></td>
        <td><%= link_to 'Edit', edit_generic_path(generic) %></td>
        <td><%= link_to 'Destroy', generic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New UNM Generic Template Form', new_generic_path %>
<% end %>

<br>
<%= link_to 'Back', mains_path %>

app/views/generics/new.html.erb
<h1>New Generic</h1>

<%= render 'form' %>

<%= link_to 'Back', generics_path %>

app/views/generics/show.html.erb
<p>
  <strong>Title of Degree or Certificate Program:</strong>
  <%= @generic.one %>
</p>

<p>
  <strong>Degree Level:</strong>
  <%= @generic.two %>
</p>

<p>
  <strong>Name of Academic Department (if relevant):</strong>
  <%= @generic.three %>
</p>

<p>
  <strong>Name of College/School/Branch:</strong>
  <%= @generic.four %>
</p>

<p>
  <strong>Academic Year/Assessment Period:</strong>
  <%= @generic.five %>
</p>

<p>
  <strong>Submitted By (include email address):</strong>
  <%= @generic.six %>
</p>

<p>
  <strong>Date Submitted to College/School/Branch for Review:</strong>
  <%= @generic.seven %>
</p>

<p>
  <strong>Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:</strong>
  <%= @generic.eight %>
</p>

<p>
  <strong>State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:</strong>
  <%= @generic.nine %>
</p>

<p>
  <strong>If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year:</strong>
  <%= @generic.ten %>
</p>

<p>
  <strong>Describe the actions and/or improvements that were implemented during the previous reporting period (provide relevant evidence):</strong>
  <%= @generic.eleven %>
</p>

<%= link_to 'Edit', edit_generic_path(@generic) %> |
<%= link_to 'Back', generics_path %>

app/views/schooles/_form.html.erb
<%= form_for(@schoole) do |f| %>
  <% if @schoole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schoole.errors.count, "error") %> prohibited this schoole from being saved:</h2>

      <ul>
      <% @schoole.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table align="center">
   <tr><td>
    Title of Degree or Certificate Program
    </td>	<td><div class="field"><% f.label :one %>
    <%= f.text_field :one %>
  </div></td>
           </tr><tr>	<td>
             Degree Level

       </td>	<td><div class="field"><% f.label :two %>
    <%= f.text_field :two %>
  </div></td>
           </tr><tr>	<td>
                Name of Academic Department:

       </td>	<td><div class="field"><% f.label :three %>
    <%= f.text_field :three %>
  </div></td>
           </tr><tr>	<td>
                Name of College/School/Branch:

       </td>	<td><div class="field"><% f.label :four %>
    <%= f.text_field :four %>
  </div></td>
           </tr><tr>	<td>
                Academic Year/Assessment Period:

       </td>	<td><div class="field"><% f.label :five %>
    <%= f.text_field :five %>
  </div></td>
           </tr><tr>	<td>
                Submitted By (include email address):

       </td>	<td><div class="field"><% f.label :six %>
    <%= f.text_field :six %>
  </div></td>
           </tr><tr>	<td>
                Date Submitted to College/School/Branch for Review:

       </td>	<td><div class="field"><% f.label :seven %>
    <%= f.date_select :seven %>
  </div></td>
           </tr><tr>	<td>
                Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:

       </td>	<td><div class="field"><% f.label :eight %>
    <%= f.date_select :eight %>
  </div></td>
           </tr><tr>	<td>
                State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:

       </td>	<td><div class="field"><% f.label :nine %>
           <%= f.text_area :nine %>
  </div></td>
           </tr><tr>	<td>
                If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year:

       </td>	<td><div class="field"><% f.label :ten %>
    <%= f.text_area :ten %>
  </div></td></tr></table>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schooles/edit.html.erb
<h1>Editing Schoole</h1>

<%= render 'form' %>

<%= link_to 'Show', @schoole %> |
<%= link_to 'Back', schooles_path %>

app/views/schooles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing School of Engineering Forms</h1>

<% if current_user.position == 'Admin' %>

<table border = '1'>
  <thead>
    <tr>
      <th>Title of Degree or Certificate Program</th>
      <th>Name of Academic Department (if relevant):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @schooles.each do |schoole| %>
      <tr>
        <td><%= schoole.one %></td>
        <td><%= schoole.three %></td>
        <td><%= schoole.seven %></td>
        <% flag = 0 %>
            <% @schoole_managers.each do |schoole_manager| %>
              <% if schoole.id == schoole_manager.schoole_id %>
                <% flag = 1 %>
                <td><%= schoole_manager.comment %></td>
                <td><%= schoole_manager.score %></td>
                <td><%= link_to 'Grade', edit_schoole_schoole_manager_path(schoole, schoole_manager.id) %></td>
              <% end %>
            <% end %>
            <% if flag == 0 %>
                <td>Need to Grade</td>
                <td>Need to Grade</td>
                <td><%= link_to 'Grade', new_schoole_schoole_manager_path(schoole) %></td>
            <% end %>
        <td><%= link_to 'Edit', edit_schoole_path(schoole) %></td>
        <td><%= link_to 'Destroy', schoole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user.position == 'Manager' %>
<table border = "1">
  <thead>
    <tr>
      <th>Title of Degree or Certificate Program</th>
      <th>Name of Academic Department (if relevant):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% if current_user.department_name == user.department_name %>
        <% identity = user.id %>
        <% @schooles.each do |schoole| %>
          <tr>
          <% if identity == schoole.user_id %>
            <td><%= schoole.one %></td>
            <td><%= schoole.three %></td>
            <td><%= schoole.seven %></td>
            <% flag = 0 %>
            <% @schoole_managers.each do |schoole_manager| %>
              <% if schoole.id == schoole_manager.schoole_id %>
                <% flag = 1 %>
                <td><%= schoole_manager.comment %></td>
                <td><%= schoole_manager.score %></td>
                <td><%= link_to 'Grade', edit_schoole_schoole_manager_path(schoole, schoole_manager.id) %></td>
              <% end %>
            <% end %>
            <% if flag == 0 %>
                <td>Need to Grade</td>
                <td>Need to Grade</td>
                <td><%= link_to 'Grade', new_schoole_schoole_manager_path(schoole) %></td>
            <% end %>
            <td><%= link_to 'Edit', edit_schoole_path(schoole) %></td>
            <td><%= link_to 'Destroy', schoole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user.position == 'User' %>

<table border = '1'>
  <thead>
    <tr>
      <th>Title of Degree or Certificate Program:</th>
      <th>Degree Level</th>
      <th>Name of Academic Department: </th>
      <th>Name of College/School/Branch:</th>
      <th>Academic Year/Assessment Period:</th>
      <th>Submitted By (include email address):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:</th>
      <th>State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:</th>
      <th>If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year:</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @schooles.each do |schoole| %>
      <tr>
      <% if current_user.id == schoole.user_id %>
        <td><%= schoole.one %></td>
        <td><%= schoole.two %></td>
        <td><%= schoole.three %></td>
        <td><%= schoole.four %></td>
        <td><%= schoole.five %></td>
        <td><%= schoole.six %></td>
        <td><%= schoole.seven %></td>
        <td><%= schoole.eight %></td>
        <td><%= schoole.nine %></td>
        <td><%= schoole.ten %></td>
        <td><%= link_to 'Show', schoole %></td>
        <td><%= link_to 'Edit', edit_schoole_path(schoole) %></td>
        <td><%= link_to 'Destroy', schoole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New School of Engineering Form', new_schoole_path %>
<% end %>

<br>
<%= link_to 'Back', mains_path %>

app/views/schooles/new.html.erb
<h1>New Schoole</h1>

<%= render 'form' %>

<%= link_to 'Back', schooles_path %>

app/views/schooles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>One:</strong>
  <%= @schoole.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @schoole.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @schoole.three %>
</p>

<p>
  <strong>Four:</strong>
  <%= @schoole.four %>
</p>

<p>
  <strong>Five:</strong>
  <%= @schoole.five %>
</p>

<p>
  <strong>Six:</strong>
  <%= @schoole.six %>
</p>

<p>
  <strong>Seven:</strong>
  <%= @schoole.seven %>
</p>

<p>
  <strong>Eight:</strong>
  <%= @schoole.eight %>
</p>

<p>
  <strong>Nine:</strong>
  <%= @schoole.nine %>
</p>

<p>
  <strong>Ten:</strong>
  <%= @schoole.ten %>
</p>

<%= link_to 'Edit', edit_schoole_path(@schoole) %> |
<%= link_to 'Back', schooles_path %>